config/routes.rb
Rails.application.routes.draw do
  root 'flights#index'
  resources :flights
  resources :bookings, except: [:index]
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :departing_flights, class_name: "Flight",
           foreign_key: "from_airport_id"
  has_many :arriving_flights, class_name: "Flight",
           foreign_key: "to_airport_id"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  has_one :from_airport, through: :flight
  has_one :to_airport, through: :flight
  has_many :passengers
  accepts_nested_attributes_for :passengers 

end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :from_airport, class_name: "Airport"
  belongs_to :to_airport,   class_name: "Airport"
  has_many :bookings
  has_many :passengers, through: :bookings
  default_scope { order(date: :asc) }
  scope :future, -> { where("date > ?", Time.now) }
  scope :on_day, ->(date) {
    day = date.to_datetime.beginning_of_day
    where(date: day..day.end_of_day)
  }

  def formatted_duration
    hours = duration / 60
    minutes = duration % 60
    "#{hours.to_s} hours and #{minutes.to_s} minutes"
  end 

end

app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :booking
  has_one :flight, through: :booking
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    num_passengers = params[:num_tickets].to_i
    @flight = Flight.find(params[:flight_id])
    @booking = @flight.bookings.build()
    num_passengers.times { @booking.passengers.build }
  end

  def create
    flight = Flight.find(params[:booking][:flight_id])
    @booking = flight.bookings.build(booking_params)
    if @booking.save
      redirect_to @booking
    else
      render 'new'
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

    #Exclude flight id since it's not necessary for building through associations
    def booking_params
      params.require(:booking).permit(:flight_id, :date, 
      passengers_attributes: [:id, :name, :email]).except(:flight_id)
    end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  before_action :set_flight, only: [:show, :edit, :update, :destroy]

  # GET /flights
  def index
    @airports = Airport.all
    dates = Flight.future.distinct.pluck(:date)
    @date_options = dates.map { |date| [ formatted_date(date), date ] }
    unless flight_params.empty?
     @flights = Flight.where(flight_params).try(:on_day, params[:date]) 
     @num_tickets = params[:num_tickets].to_s
    end
  end

  # GET /flights/1
  def show
  end

  # GET /flights/new
  def new
    @flight = Flight.new
  end

  # GET /flights/1/edit
  def edit
  end

  # POST /flights
  def create
    @flight = Flight.new(flight_params)

    if @flight.save
      redirect_to @flight, notice: 'Flight was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /flights/1
  def update
    if @flight.update(flight_params)
      redirect_to @flight, notice: 'Flight was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /flights/1
  def destroy
    @flight.destroy
    redirect_to flights_url, notice: 'Flight was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flight
      @flight = Flight.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def flight_params
      params.permit(:to_airport_id, :from_airport_id, 
                    :num_tickets, :date).except(:num_tickets, :date)
    end

    # Format a date.
    def formatted_date(date)
      date.strftime("%m/%d/%Y")
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def formatted_datetime(date)
    date.strftime("%l:%M %p %m/%-d/%y")
  end
  
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/_booking_form.html.erb
<%= form_for(@booking) do |f| %>

  <h3>Flight Information:</h3>
  <p>From <%= @flight.from_airport.code %> to <%= @flight.to_airport.code %></p>
  <p>When: <%= formatted_datetime(@flight.date) %></p>

  <%= f.hidden_field :flight_id, value: @flight.id %>
  <%= f.hidden_field :date, value: @flight.date %>

  <% @booking.passengers.each_with_index do |passenger, index| %>
    <h4><%= (index + 1).ordinalize %> Passenger:</h4> 
    <%= f.fields_for :passengers, passenger do |passenger_form| %>

      <%= passenger_form.label :name %>
      <%= passenger_form.text_field :name %>
      
      <%= passenger_form.label :email %>
      <%= passenger_form.text_field :email %>
    
   <% end %>
  <% end %>
  
  <%= f.submit "Book flight" %>

<% end %>

app/views/bookings/destroy.html.erb
<h1>Bookings#destroy</h1>
<p>Find me in app/views/bookings/destroy.html.erb</p>

app/views/bookings/edit.html.erb
<h1>Bookings#edit</h1>
<p>Find me in app/views/bookings/edit.html.erb</p>

app/views/bookings/new.html.erb
<h1>Book a Flight</h1>

<%= render 'booking_form' %>

app/views/bookings/show.html.erb
<h1>Booking for <%= @booking.passengers.pluck(:name).join(', ') %></h1>

<h2>From <%= @booking.from_airport.code %> to <%= @booking.to_airport.code %></h2>

<h2>Time: <%= formatted_datetime(@booking.date) %></h2>

<h3>Passengers:<h3>
<ol>
  <% @booking.passengers.each do |passenger| %>
    <li><%= passenger.name %>
  <% end %>
</ol>

app/views/bookings/update.html.erb
<h1>Bookings#update</h1>
<p>Find me in app/views/bookings/update.html.erb</p>

app/views/flights/_form.html.erb
<%= form_with(model: flight, local: true) do |form| %>
  <% if flight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(flight.errors.count, "error") %> prohibited this flight from being saved:</h2>

      <ul>
      <% flight.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/flights/_search_form.html.erb
<%= form_tag(root_path, method: :get) do %>
  <%= label_tag :from_airport_id, "From:" %>
  <%= select_tag :from_airport_id, options_from_collection_for_select(@airports,
                                :id, :code) %>
  
  <%= label_tag :to_airport_id, "Destination:" %>
  <%= select_tag :to_airport_id, options_from_collection_for_select(@airports,
                                :id, :code) %>

  <%= label_tag :num_tickets, "Number of passengers:" %>
  <%= select_tag :num_tickets, options_for_select([[1,1],[2,2],[3,3],[4,4]]) %>
  
  <%= label_tag :date, "Date:" %>
  <%= select_tag :date, options_for_select(@date_options) %>

  <%= submit_tag "Search" %>

<% end %>

app/views/flights/edit.html.erb
<h1>Editing Flight</h1>

<%= render 'form', flight: @flight %>

<%= link_to 'Show', @flight %> |
<%= link_to 'Back', flights_path %>

app/views/flights/index.html.erb
<h1>Flights</h1>

<%= render 'search_form' %>

<% if @flights %>
  <h1> Available Flights: </h1>
  <%= form_tag(new_booking_path, method: :get) do %>

    <%= hidden_field_tag :num_tickets, @num_tickets %>

    <% @flights.each do |flight| %>
      <h3><%= flight.from_airport.code %> to <%=flight.to_airport.code %></h3>

      <p>Time of departure: <%= formatted_datetime(flight.date) %></p>

      <p>Duration: <%= flight.formatted_duration %> </p>
      
      <%= label_tag :flight_id, "Book #{ pluralize(@num_tickets, 'person') }" %>
      <%= radio_button_tag :flight_id, flight.id %> 
    <% end %>

    <%= submit_tag "Book Flight" %>

  <% end %>

<% end %>

app/views/flights/new.html.erb
<h1>New Flight</h1>

<%= render 'form', flight: @flight %>

<%= link_to 'Back', flights_path %>

app/views/flights/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_flight_path(@flight) %> |
<%= link_to 'Back', flights_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFlightBooker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= link_to "Home", root_path %>
  </body>
</html>